accounts/urls.py
from django.urls import path
from .views import (
    Login,
    SignUpView,
    UserProfileView,
    EditUserView,
    LogoutView,
    UsersList,
)

app_name = "accounts"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("register/", SignUpView.as_view(), name="register"),
    path("edit/", EditUserView.as_view(), name="edit_user"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("<str:username>/", UserProfileView.as_view(), name="user_profile"),
    path("", UsersList.as_view(), name="users_list"),
]

article/urls.py
from django.urls import path
from .views import (
    ArticlesListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleEditView,
    ArticleDeleteView,
)

app_name = "article"

urlpatterns = [
    path("", ArticlesListView.as_view(), name="articles_list"),
    path("<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("<int:pk>/edit/", ArticleEditView.as_view(), name="article_edit"),
    path("<int:pk>/delete/", ArticleDeleteView.as_view(), name="article_delete"),
    path("create/", ArticleCreateView.as_view(), name="article_create"),
]

cpblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("hitcount/", include(("hitcount.urls", "hitcount"), namespace="hitcount")),
    path("admin/", admin.site.urls),
    path("users/", include("accounts.urls")),
    path("", include("article.urls")),
    path("problems/", include("problem.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problem/urls.py
from django.urls import path
from .views import (
    ProblemListView,
    ProblemDetailView,
    ProblemCreateView,
    ProblemEditView,
    ProblemDeleteView,
)

app_name = "problem"

urlpatterns = [
    path("", ProblemListView.as_view(), name="problems_list"),
    path("<int:pk>/", ProblemDetailView.as_view(), name="problem_detail"),
    path("<int:pk>/edit/", ProblemEditView.as_view(), name="problem_edit"),
    path("<int:pk>/delete/", ProblemDeleteView.as_view(), name="problem_delete"),
    path("create/", ProblemCreateView.as_view(), name="problem_create"),
]

problem/models.py
from django.db import models
from accounts.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from ckeditor_uploader.fields import RichTextUploadingField
from hitcount.models import HitCount
from django.contrib.contenttypes.fields import GenericRelation

# Create your models here.


class Problem(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    reputation = models.IntegerField(default=0)
    description = RichTextUploadingField()
    difficulty = models.IntegerField(
        default=1, validators=(MinValueValidator(1), MaxValueValidator(100))
    )
    is_active = models.BooleanField(default=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)
    hit_count_generic = GenericRelation(
        HitCount,
        object_id_field="object_pk",
        related_query_name="hit_count_generic_relation",
    )

    class Meta:
        ordering = ["-created_time"]

    def __str__(self) -> str:
        return self.title

problem/forms.py
from django.forms import ModelForm
from .models import Problem


class ProblemCreateForm(ModelForm):
    class Meta:
        model = Problem
        fields = ("title", "url", "description", "difficulty")

problem/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from hitcount.views import HitCountDetailView
from .models import Problem
from .forms import ProblemCreateForm

# Create your views here.


class ProblemListView(ListView):
    model = Problem
    context_object_name = "problems"
    template_name = "problems/problem_list.html"


class ProblemDetailView(UpdateView, HitCountDetailView):
    model = Problem
    context_object_name = "problem"
    template_name = "problems/problem_detail.html"
    fields = ["reputation"]
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == "POST":
            print(self.request.POST)
            plus = self.request.POST.get("plus")
            minus = self.request.POST.get("minus")
            if minus:
                problem = self.get_object()
                problem.reputation -= 1
                # problem.owner.reputation -= 1
                problem.save()
            if plus:
                problem = self.get_object()
                problem.reputation += 1
                # problem.owner.reputation += 1
                problem.save()
        return context


class ProblemCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("accounts:login")
    model = Problem

    def get(self, r):
        form = ProblemCreateForm
        return render(r, "problems/problem_create.html", {"form": form})

    def post(self, r):
        form = ProblemCreateForm(r.POST)
        if form.is_valid():
            problem = form.save(commit=False)
            problem.owner = self.request.user
            problem.save()
            return redirect("problem:problem_detail", pk=problem.pk)


class ProblemEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Problem
    login_url = reverse_lazy("accounts:login")
    template_name = "problems/problem_edit.html"
    fields = ("title", "url", "description", "difficulty")

    def get_success_url(self) -> str:
        return reverse("problem:problem_detail", kwargs={"pk": self.get_object().pk})

    def test_func(self):
        return (
            self.request.user.username == self.get_object().owner.username
            or self.request.user.is_superuser
        )


class ProblemDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Problem
    template_name = "problems/problem_delete.html"
    login_url = reverse_lazy("accounts:login")
    success_url = reverse_lazy("problem:problems_list")

    def test_func(self):
        return (
            self.request.user.username == self.get_object().owner.username
            or self.request.user.is_superuser
        )

templates/problems/problem_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/problem.css' %}" type="text/css">
    <title>{% block title %}{% endblock title %}</title>
    <script src="https://kit.fontawesome.com/3d927a6073.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <div class="flex-container">
            <div class="flex-left header__logo header__item">
                <a href="{% url 'article:articles_list' %}"> CPBlog.uz </a> 
            </div>
            <div class="flex-center">
                <div class="header__articles header__item">
                    <a href="{% url 'article:articles_list' %}">Maqolalar</a> 
                </div>
                <div class="header__problems header__item">
                    <a href="{% url 'problem:problems_list' %}">Masalalar</a> 
                </div>
            </div>
            <div class="flex-right">
                {% if request.user.is_authenticated %}
                <div class="header__right header__item">
                    <a href="{% url 'problem:problem_create' %}">
                        <i class="fa-solid fa-circle-plus" style="font-size: 25px;"></i>
                    </a>
                </div>
                <div class="header__right header__item">
                    <a href="{% url 'accounts:user_profile' request.user.username%}">
                        <i class="fa-solid fa-circle-user" style="font-size: 25px;"></i>
                    </a> 
                </div>
                <div class="header__right header__item">
                    <a href="{% url 'accounts:logout' %}">
                        <i class="fa-solid fa-right-from-bracket" style="font-size: 25px;"></i>
                    </a> 
                </div>
                {% else %}
                    <div class="header__right header__item">
                        <a href="{% url 'accounts:login' %}">
                            <i class="fa-solid fa-right-to-bracket" style="font-size: 25px;"></i>
                        </a> 
                    </div>
                {% endif %}
            </div>
        </div>
        <hr>
    </header>

    <nav>
        <ul class="category__list">
            {% for category in categories %}
                <li class="category__list__item">
                    <a href="/problems/?category={{category.name}}">
                        {% comment %} <i class="fa-solid fa-circle-chevron-down" style="margin-right: 2px;"></i> {% endcomment %}
                        {{category.name}}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </nav>

    <section>
        {% block content %}
        {% endblock content %}
    </section>
</body>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
</html>

templates/problems/problem_create.html
{% extends 'problems/problem_base.html' %}

{% block title %}Masala qo'shish{% endblock title %}

{% block content %}
    <h3 class="problem-title">Yangi masala qo'shish</h3>
    <form method="post"> {% csrf_token %}
        {{form.as_p}}
        {{form.media}}
        <button type="submit">Saqlash</button>
    </form>
{% endblock content%}

templates/problems/problem_delete.html
{% extends 'problems/problem_base.html' %}

{% block title %}Delete{% endblock title %}

{% block content %}
    <h3 class="problem-title danger">{{problem.title}} masalasini o'chirishingizni tasdiqlang.</h3>
    <form method="post">{% csrf_token %}
        <button type="submit"> Tasdiqlayman </button>
    </form>
{% endblock content %}

templates/problems/problem_detail.html
{% extends 'problems/problem_base.html' %}
{% load hitcount_tags %}

{% block title %} {{ problem.title | truncatewords:3 }} {% endblock title %}

{% block content %}
    <h5 style="margin: 15px 15px 15px 30px; float: right;">
        {% if request.user.username == problem.owner.username or request.user.is_superuser %}
            <span class="problem-data">
                <a href="{% url 'problem:problem_edit' problem.pk %}">
                    Tahrirlash
                </a>
            </span>
            {% if problem.reputation < 10 %}
                <span class="problem-data danger">
                    <a href="{% url 'problem:problem_delete' problem.pk %}">
                        O'chirish
                    </a>
                </span>
            {% endif %}
        {% endif %}
        <span class="problem-data">{{problem.created_time | date:'Y-m-d H:i'}}</span>
        <span class="problem-data">
            <i class="fa-solid fa-eye"></i>
            <span style="margin-left:5px;">{% get_hit_count for problem %}</span>
        </span>
        <span class="problem-data">
            <span>Ulashdi:&nbsp</span>
            <a href="{% url 'accounts:user_profile' problem.owner.username %}">
                {{problem.owner.username}}
            </a>
        </span>
    </h5>
    <h3 class="problem-title">
        <a href="{{problem.url}}">{{problem.title}}</a>
    </h3>
    
    <article class="problem-body">
        <h5 style="font-size: 18px;">
            <a href="{{problem.url}}">Masalaga o'tish</a>
        </h5>
        {{problem.description|safe}}
    </article>
    <div class="vote-box">
        <form method="post" class="vote">
            {% csrf_token %}
            <button name="plus" value="plus" style="color: rgba(144, 238, 144, 0.8);" type="submit"><i class="fa-solid fa-circle-chevron-up"></i></button>
        </form>
        <span class="vote"
            style="color:
            {% if problem.reputation < 0 %}
                rgb(220, 105, 105); 
            {% elif problem.reputation == 0 %}
                #cfcfcf
            {% else %}
                rgba(144, 238, 144, 0.8);
            {% endif %}">
            {{problem.reputation}}
        </span>
        <form method="post" class="vote">
            {% csrf_token %}
            <button name="minus" value="minus" style="color: rgb(220, 105, 105);" type="submit"><i class="fa-solid fa-circle-chevron-down"></i></button>
        </form>
    </div>
{% endblock content %}

templates/problems/problem_edit.html
{% extends 'problems/problem_base.html' %}

{% block title %}Masalani tahrirlash{% endblock title %}

{% block content %}
    <h3 class="problem-title">Masalani tahrirlash</h3>
    <form method="post"> {% csrf_token %}
        {{form.as_p}}
        {{form.media}}
        <button type="submit">Saqlash</button>
    </form>
{% endblock content %}

templates/problems/problem_list.html
{% extends 'problems/problem_base.html' %}
{% load hitcount_tags %}
{% block title %} Masalalar {% endblock title %}

{% block content %}
    {% for problem in problems %}
        <div class="problem-list">
            <div style="float:left; width: 30%;">
                <h3>
                    <a href="{% url 'problem:problem_detail' problem.pk %}">
                        {{problem.title}}
                    </a>
                </h3>
                <h5>
                    {{problem.created_time | date:'Y-m-d H:i'}}
                    {% get_hit_count for problem %}
                    <a href="{% url 'accounts:user_profile' problem.owner.username %}">
                        {{problem.owner.username}}
                    </a>
                </h5>
            </div>
            <div style="float:right; width: 68%;">
                {{problem.description | truncatechars:500 | safe}}
            </div>
            <div class="clear"></div>
        </div>
    {% endfor %}
{% endblock content %}