accounts/urls.py
from django.urls import path
from .views import (
    Login,
    SignUpView,
    UserProfileView,
    EditUserView,
    LogoutView,
    UsersList,
)

app_name = "accounts"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("register/", SignUpView.as_view(), name="register"),
    path("edit/", EditUserView.as_view(), name="edit_user"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("<str:username>/", UserProfileView.as_view(), name="user_profile"),
    path("", UsersList.as_view(), name="users_list"),
]

article/urls.py
from django.urls import path
from .views import (
    ArticlesListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleEditView,
    ArticleDeleteView,
)

app_name = "article"

urlpatterns = [
    path("", ArticlesListView.as_view(), name="articles_list"),
    path("<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("<int:pk>/edit/", ArticleEditView.as_view(), name="article_edit"),
    path("<int:pk>/delete/", ArticleDeleteView.as_view(), name="article_delete"),
    path("create/", ArticleCreateView.as_view(), name="article_create"),
]

cpblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("hitcount/", include(("hitcount.urls", "hitcount"), namespace="hitcount")),
    path("admin/", admin.site.urls),
    path("users/", include("accounts.urls")),
    path("", include("article.urls")),
    path("problems/", include("problem.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problem/urls.py
from django.urls import path
from .views import (
    ProblemListView,
    ProblemDetailView,
    ProblemCreateView,
    ProblemEditView,
    ProblemDeleteView,
)

app_name = "problem"

urlpatterns = [
    path("", ProblemListView.as_view(), name="problems_list"),
    path("<int:pk>/", ProblemDetailView.as_view(), name="problem_detail"),
    path("<int:pk>/edit/", ProblemEditView.as_view(), name="problem_edit"),
    path("<int:pk>/delete/", ProblemDeleteView.as_view(), name="problem_delete"),
    path("create/", ProblemCreateView.as_view(), name="problem_create"),
]

article/models.py
from django.db import models
from accounts.models import User
from main.models import Category
from ckeditor_uploader.fields import RichTextUploadingField
from hitcount.models import HitCount
from django.contrib.contenttypes.fields import GenericRelation


class Article(models.Model):
    title = models.CharField(max_length=255)
    body = RichTextUploadingField()
    reputation = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category)
    hit_count_generic = GenericRelation(
        HitCount,
        object_id_field="object_pk",
        related_query_name="hit_count_generic_relation",
    )

    class Meta:
        ordering = ["-created_time"]

    def __str__(self) -> str:
        return self.title

article/forms.py
from django.forms import ModelForm
from .models import Article


class ArticleCreateForm(ModelForm):
    class Meta:
        model = Article
        fields = ["title", "body", "categories"]

article/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .forms import ArticleCreateForm
from .models import Article
from hitcount.views import HitCountDetailView
from django.views import View
from django.views.generic import (
    CreateView,
    DeleteView,
    UpdateView,
)


class ArticlesListView(View):
    def get(self, request):
        articles = Article.objects.all()
        category = request.GET.get("category")
        # print(category)
        if category:
            category = list(category.split(","))
            for i in category:
                articles = articles.filter(categories__name=i)
        return render(request, "articles/articles_list.html", {"articles": articles})


class ArticleDetailView(UpdateView, HitCountDetailView):
    model = Article
    template_name = "articles/article_detail.html"
    context_object_name = "article"
    fields = ["reputation"]
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == "POST":
            print(self.request.POST)
            plus = self.request.POST.get("plus")
            minus = self.request.POST.get("minus")
            if minus:
                article = self.get_object()
                article.reputation -= 1
                # article.owner.reputation -= 1
                article.save()
            if plus:
                article = self.get_object()
                article.reputation += 1
                # article.owner.reputation += 1
                article.save()

        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("accounts:login")
    model = Article

    def get(self, r):
        form = ArticleCreateForm
        return render(r, "articles/article_create.html", {"form": form})

    def post(self, r):
        form = ArticleCreateForm(r.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.owner = r.user
            article.save()
            return redirect("article:article_detail", pk=article.pk)


class ArticleEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = ("title", "body", "categories")
    login_url = reverse_lazy("accounts:login")
    template_name = "articles/article_edit.html"

    def get_success_url(self):
        return reverse_lazy(
            "article:article_detail", kwargs={"pk": self.get_object().pk}
        )

    def test_func(self):
        return (
            self.request.user.username == self.get_object().owner.username
            or self.request.user.is_superuser
        )


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    login_url = reverse_lazy("accounts:login")
    template_name = "articles/article_delete.html"

    def get_success_url(self):
        return reverse_lazy("article:articles_list")

    def test_func(self):
        return (
            self.request.user.username == self.get_object().owner.username
            or self.request.user.is_superuser
        )

templates/articles/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Article</title>
</head>
<body>
    <h3>{{article.title}}</h3>
    <h5>
        {{article.created_time | date:'Y-m-d H:i'}}
        {{article.reputation}}
        <a href="{% url 'user_profile' article.owner.username %}">{{article.owner}}</a>
    </h5>
    <article>{{article.body}}</article>
</body>
</html>

templates/articles/article_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/article.css' %}" type="text/css">
    <title>{% block title %}{% endblock title %}</title>
    <script src="https://kit.fontawesome.com/3d927a6073.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <div class="flex-container">
            <div class="flex-left header__logo header__item">
                <a href="{% url 'article:articles_list' %}"> CPBlog.uz </a> 
            </div>
            <div class="flex-center">
                <div class="header__articles header__item">
                    <a href="{% url 'article:articles_list' %}">Maqolalar</a> 
                </div>
                <div class="header__problems header__item">
                    <a href="{% url 'problem:problems_list' %}">Masalalar</a> 
                </div>
            </div>
            <div class="flex-right">
                {% if request.user.is_authenticated %}
                <div class="header__right header__item">
                    <a href="{% url 'article:article_create' %}">
                        <i class="fa-solid fa-circle-plus" style="font-size: 23px;"></i>
                    </a>
                </div>
                <div class="header__right header__item">
                    <a href="{% url 'accounts:users_list' %}">
                        <i class="fa-solid fa-user-group" style="font-size: 23px;"></i>
                    </a>
                </div>
                <div class="header__right header__item">
                    <a href="{% url 'accounts:user_profile' request.user.username%}">
                        <i class="fa-solid fa-user" style="font-size: 23px;"></i>
                    </a> 
                </div>
                <div class="header__right header__item">
                    <a href="{% url 'accounts:logout' %}">
                        <i class="fa-solid fa-right-from-bracket" style="font-size: 23px;"></i>
                    </a> 
                </div>
                {% else %}
                    <div class="header__right header__item">
                        <a href="{% url 'accounts:login' %}">
                            <i class="fa-solid fa-right-to-bracket" style="font-size: 25px;"></i>
                        </a> 
                    </div>
                {% endif %}
            </div>
        </div>
        <hr>
    </header>

    <nav>
        <ul class="category__list">
            {% for category in categories %}
                <li class="category__list__item">
                    <a href="/?category={{category.name}}">
                        {% comment %} <i class="fa-solid fa-circle-chevron-down" style="margin-right: 2px;"></i> {% endcomment %}
                        {{category.name}}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </nav>

    <section>
        {% block content %}
        {% endblock content %}
    </section>
</body>
{% block script %}{% endblock script %}
</html>

templates/articles/article_create.html
{% extends 'articles/article_base.html' %}

{% block title %}Maqola yaratish{% endblock title %}

{% block content %}
    <h3 class="article-title">Yangi maqola yaratish</h3>
    <form method="post"> {% csrf_token %}
        {{form.as_p}}
        {{form.media}}
        <button type="submit">Saqlash</button>
    </form>
{% endblock content%}

templates/articles/article_delete.html
{% extends 'articles/article_base.html' %}

{% block title %}Delete{% endblock title %}

{% block content %}
    <h3 class="article-title danger">{{article.title}} postini o'chirishingizni tasdiqlang.</h3>
    <form method="post">{% csrf_token %}
        <button type="submit"> Tasdiqlayman </button>
    </form>
{% endblock content %}

templates/articles/article_detail.html
{% extends 'articles/article_base.html' %}
{% load hitcount_tags %}

{% block title %}{{article.title | truncatewords:3}}{% endblock title %}

{% block content %}
    <h5 style="margin: 15px 15px 15px 30px; float: right;">
        {% if request.user.username == article.owner.username or request.user.is_superuser %}
            <span class="article-data">
                <a href="{% url 'article:article_edit' article.pk %}">
                    Tahrirlash
                </a>
            </span>
            {% if article.reputation < 10 %}
                <span class="article-data danger">
                    <a href="{% url 'article:article_delete' article.pk %}">
                        O'chirish
                    </a>
                </span>
            {% endif %}
        {% endif %}
        <span class="article-data">{{article.created_time | date:'Y-m-d H:i'}}</span>
        <span class="article-data">
            <i class="fa-solid fa-eye"></i>
            <span style="margin-left:5px;">{% get_hit_count for article %}</span>
        </span>
        <span class="article-data">
            <span>Muallif:&nbsp</span>
            <a href="{% url 'accounts:user_profile' article.owner.username %}">
                {{article.owner.username}}
            </a>
        </span>
    </h5>
    <h3 class="article-title">{{article.title}}</h3>
    <article class="article-body">{{article.body|safe}}</article>
    <div class="vote-box">
        <form method="post" class="vote">
            {% csrf_token %}
            <button name="plus" value="plus" style="color: rgba(144, 238, 144, 0.8);" type="submit"><i class="fa-solid fa-circle-chevron-up"></i></button>
        </form>
        <span class="vote"
            style="color:
            {% if article.reputation < 0 %}
                rgb(220, 105, 105); 
            {% elif article.reputation == 0 %}
                #cfcfcf
            {% else %}
                rgba(144, 238, 144, 0.8);
            {% endif %}">
            {{article.reputation}}
        </span>
        <form method="post" class="vote">
            {% csrf_token %}
            <button name="minus" value="minus" style="color: rgb(220, 105, 105);" type="submit"><i class="fa-solid fa-circle-chevron-down"></i></button>
        </form>
    </div>
{% endblock content %}  

{% block script %}
    <script type="text/javascript" id="MathJax-script" async
    src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
    </script>
{% endblock script %}

templates/articles/article_edit.html
{% extends 'articles/article_base.html' %}

{% block title %}Maqolani tahrirlash{% endblock title %}

{% block content %}
    <h3 class="article-title">Maqolani tahrirlash</h3>
    <form method="post"> {% csrf_token %}
        {{form.as_p}}
        {{form.media}}
        <button type="submit">Saqlash</button>
    </form>
{% endblock content %}

templates/articles/articles_list.html
{% extends 'articles/article_base.html' %}
{% load static %}
{% load hitcount_tags %}

{% block title %}Maqolalar{% endblock title %}

{% block content %}
    {% for article in articles %}
        <div class="article-list">
            <div style="float:left; width: 30%;">
                <h3>
                    <a href="{% url 'article:article_detail' article.pk %}">
                        {{article.title}}
                    </a>
                </h3>
                <h5>
                    {{article.created_time | date:'Y-m-d H:i'}}
                    {% get_hit_count for article %}
                    <a href="{% url 'accounts:user_profile' article.owner.username %}">
                        {{article.owner}}
                    </a>
                </h5>
            </div>
            <div class="clear"></div>
        </div>
    {% endfor %}
{% endblock content %}